---

- name: "[amavis] stop freshclam before configure"
  service: name=clamav-freshclam state=stopped

- lineinfile:
    dest=/etc/clamav/freshclam.conf
    regexp='^HTTPProxyServer'
    line="HTTPProxyServer {{amavis.freshclam_proxy_server}}"
    state=present
  when: amavis.freshclam_proxy_server is defined

- lineinfile:
    dest=/etc/clamav/freshclam.conf
    regexp='^HTTPProxyPort'
    line="HTTPProxyPort {{amavis.freshclam_proxy_port}}"
    state=present
  when: amavis.freshclam_proxy_server is defined

- lineinfile:
    dest=/etc/clamav/clamd.conf
    regexp='^AllowSupplementaryGroups'
    line='AllowSupplementaryGroups true'
    state=present

- lineinfile:
    dest=/etc/spamassassin/local.cf
    line='use_bayes 0'
    state=present

- name: "[amavis] add clamav to amavis group"
  user: name=clamav groups=amavis append=yes

- name: "[amavis] add amavis to clamav group"
  user: name=amavis groups=clamav append=yes

- name: "[amavis] update clam sigs"
  command: /usr/bin/freshclam

- name: "[amavis] start freshclam"
  service: name=clamav-freshclam state=started enabled=yes

- name: "[amavis] start clamd"
  service: name=clamav-daemon state=started enabled=yes

- name: "set up mailname"
  template: src=templates/mailname dest=/etc/mailname owner=root group=root mode=644

- name: "[amavis] configure 52-ansible"
  template: src=templates/52-ansible.j2 dest=/etc/amavis/conf.d/52-ansible owner=root group=root mode=0644
  notify:
    - reload amavis
  tags:
    - config

- name: "[amavis] add SH DQS key"
  template: src=templates/sh.cf.j2 dest=/etc/spamassassin/sh.cf owner=root group=root mode=0644
  when: amavis.enable_dqs is true
  notify:
    - reload amavis
  tags:
    - config

- name: "[amavis] enable service"
  service: name=amavis state=started enabled=yes
