---
- name: install spam check packages
  yum:
    name: ['amavisd-new', 'clamav-daemon', 'spamassassin', 'unrar-free', 'arj', 'cabextract', 'arc', 'p7zip-full', 'bzip2']
    state: present
    update_cache: yes

