---
- name: install spam check packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - amavisd-new
    - clamav
    - spamassassin
    - unrar-free
    - arj
    - cabextract
    - arc
    - p7zip-full
    - bzip2

